apiVersion: apps/v1
kind: Deployment
metadata:
  labels:  
    {{- include "redissyncer-chart.labels" . | nindent 4 }}
  name: {{ include "redissyncer-chart.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "redissyncer-chart.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:     
        {{- include "redissyncer-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers: 
      - name: redissyncer-server
        image: "{{ .Values.image.redissyncer_server.repository }}:{{ .Values.image.redissyncer_server.tag | default "latest" }}"       
        imagePullPolicy: {{ .Values.image.redissyncer_server.pullPolicy }}  
        env:
        - name: JAVA_TOOL_OPTIONS
          value: {{.Values.env.JAVA_TOOL_OPTIONS}}
        - name: SPRING_ENV
          value: {{.Values.env.SPRING_ENV}}
        resources:
          limits:
            memory: "4294967296"
        volumeMounts:
        - name: data
          mountPath: "/redissyncer"      
        ports:
        - containerPort: 8080
      - name: redissyncer-dashboard
        image: "{{ .Values.image.redissyncer_dashboard.repository }}:{{ .Values.image.redissyncer_dashboard.tag | default "latest" }}"  
        imagePullPolicy: {{ .Values.image.redissyncer_dashboard.pullPolicy }}        
        ports:
        - containerPort: 3000
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "redissyncer-chart.fullname" . }}


