{{- if .Values.ingress.enabled -}}
{{- $fullName := include "redissyncer-chart.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  # name: redissyncer-ingress-traefik
  name: {{ $fullName }}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: redissyncer.web
    http:
      paths:
      - path: /
        backend:
          # serviceName: redissyncer-service-withweb
          serviceName: {{ $fullName }}
          servicePort: 3000
  - host: redissyncer.server
    http:
      paths:
      - path: /
        backend:
          # serviceName: redissyncer-service-withweb
          serviceName: {{ $fullName }}
          servicePort: 8080
{{- end}}