{{- if .Values.ingress.enabled -}}
{{- $fullName := include "redissyncer-chart.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  annotations:
    # kubernetes.io/ingress.class: kong
spec:
  rules:
  - host: redissyncer.web
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $fullName }}
          servicePort: 3000
  - host: redissyncer.server
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $fullName }}
          servicePort: 8080
{{- end}}