apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # name: redissyncer-pv-claim
  name: {{ include "redissyncer-chart.fullname" . }}
  labels:
    {{- include "redissyncer-chart.labels" . | nindent 4 }}  
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi