apiVersion: v1
kind: Service
metadata:
  name: {{ include "redissyncer-chart.fullname" . }}
  labels:
    {{- include "redissyncer-chart.labels" . | nindent 4 }}
spec:
  ports:
    - name: web
      protocol: TCP
      port: 3000
      targetPort: 3000 
    - name: server
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    # app: redissyncer
    {{- include "redissyncer-chart.selectorLabels" . | nindent 4 }}
